### ISSUE TITLE
Not possible debug REST Application

### ISSUE THREAD

**Issue by brunobuzzi** [brunobuzzi/OrbeonPersistenceLayer#382]

**Comment by dalehenrich** [comment]
@brunobuzzi , if you are using a headless topaz/gem session to run your REST server, and you are using 3.5.1 or later, you can attach to a headless topaz or gem using the topaz `debuggem` command.  Look at the help for debuggem in topaz to get more details ...

**Comment by brunobuzzi** [comment]
@dalehenrich good to know about debuggem i going to try it. But i think i have another problem because in an interactive mode (Jade) the halt is being ignore and also self foo does not rise a DNU.

**Comment by dalehenrich** [comment]
Ah ... that is interesting ... especially if it happens in an already interactive session ... are you using [gsAppliationTools](https://github.com/GsDevKit/gsApplicationTools)? if so, I might be able to help you figure out how to debug things, since error handling might need special care ...

**Comment by brunobuzzi** [comment]
@dalehenrich 
`DEBUGGEM 3948 14341364350683474686` is nice but it seem intended when you have a DNU and you want to analyze the stack... (or the Gem is stuck). Is this correct ?
I'm trying to figure it out why a halt or a DNU is being ignored by the REST services.
On 3.5.1 with a previous version of Seaside worked correctly. A halt on Jade popup a debugger and that was it.
Maybe something changed or maybe i did something worng that is causing this problem ..

**Comment by brunobuzzi** [comment]
@dalehenrich and yes i'm using **gsAppliationTools**

**Comment by brunobuzzi** [comment]
@dalehenrich 
:) forget about this 
Is not a GS problem rather a problem in the interaction between Java Services

**Comment by brunobuzzi** [comment]
Just for the record. This problem is the same as #379 
The `lock` and `unlock` verbs are not part of Seaside REST.
When OrbeonPersistenceApi it add these two methods to `WARouteBuilder`
http://forum.world.st/Lock-and-Unlock-http-verbs-td5080242.html

But the following has to be execute to compute the routes again:
`WARouteBuilder initialize.`

**Comment by dalehenrich** [comment]
regarding using debuggem, you correct in assuming that it is most useful for debugging hung gems, however, since you CAN execute `System listenForDebugConnection` from within a gem or topaz session, it is possible to arrange for an error handler to initiate a listenForDebugConnection and then go into a loop waiting for a debuggem session to attach ... the token can be written to the log file ... this kind of thing shouldn't be done in a production setting (dumping stacks to object log is the recommended approach for production), but it can be used as I describe in test settings where hard to reproduce issues show up infrequently or any other place where running interactive gems isn't practical ...
